'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import './cart.css';import './cart-recommendations.css';import './cart-coupon.css';
type Item={id:string;variantId?:string;sku?:string;name:string;price:number;quantity:number;size?:string;colour?:string;image?:string;stock?:number};type Rec={id:string;name:string;slug:string;retail_price:number;images:string[]};type Coupon={code:string;discount:number;message:string};
export default function Cart(){
 const[items,setItems]=useState<Item[]>([]),[done,setDone]=useState(''),[recs,setRecs]=useState<Rec[]>([]),[couponInput,setCouponInput]=useState(''),[coupon,setCoupon]=useState<Coupon|null>(null),[couponMessage,setCouponMessage]=useState(''),[checking,setChecking]=useState(false);
 useEffect(()=>setItems(JSON.parse(sessionStorage.getItem('cart')||'[]')),[]);
 useEffect(()=>{setCoupon(null);setCouponMessage('');if(!items.length)return;fetch(`/api/recommendations?ids=${items.map(x=>x.id).join(',')}`).then(r=>r.ok?r.json():[]).then(setRecs).catch(()=>setRecs([]))},[items]);
 const save=(next:Item[])=>{setItems(next);sessionStorage.setItem('cart',JSON.stringify(next));window.dispatchEvent(new Event('cart-updated'))};const subtotal=items.reduce((n,x)=>n+x.price*x.quantity,0),discount=Math.min(coupon?.discount||0,subtotal),total=Math.max(0,subtotal-discount);
 async function apply(){if(!couponInput.trim())return setCouponMessage('Enter a coupon code.');setChecking(true);const r=await fetch('/api/coupons/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:couponInput,items:items.map(x=>({product_id:x.id,quantity:x.quantity}))})});const d=await r.json().catch(()=>null);setChecking(false);if(r.ok){setCoupon({code:d.code,discount:d.discount,message:d.message});setCouponMessage('')}else{setCoupon(null);setCouponMessage(d?.error||'Unable to apply coupon.')}}
 async function checkout(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const customer=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,items:items.map(x=>({product_id:x.id,variant_id:x.variantId||null,quantity:x.quantity,colour:x.colour||null})),coupon_code:coupon?.code})});if(r.ok){save([]);setDone('Order placed successfully. We will contact you shortly.')}else setDone((await r.json().catch(()=>null))?.error||'Please check your checkout details and try again.')}
 if(!items.length&&!done)return <main className="cart-page"><section className="cart-empty"><span>🛒</span><h1>Your cart is empty</h1><p>Find something comfortable for every day.</p><Link href="/shop">Continue Shopping</Link></section></main>;
 return <main className="cart-page"><div className="cart-heading"><div><p>YOUR BAG</p><h1>Your Cart</h1></div><Link href="/shop">← Continue Shopping</Link></div><div className="cart-layout"><section className="cart-items-panel"><h2>{items.length} {items.length===1?'item':'items'} in your cart</h2><div className="cart-items">{items.map((x,i)=><article key={`${x.id}-${x.variantId||x.size||''}`} className="cart-item"><div className="cart-image">{x.image?<img src={x.image} alt={x.name}/>:<span>Punjab Hosiery</span>}</div><div className="cart-item-info"><h3>{x.name}</h3>{x.size&&<p>Size: <b>{x.size}</b></p>}{x.colour&&<p>Colour: <b>{x.colour}</b></p>}<strong>₹{x.price}</strong><button className="cart-remove" onClick={()=>save(items.filter((_,j)=>j!==i))}>Remove</button></div><div className="cart-quantity"><button onClick={()=>save(items.map((a,j)=>j===i?{...a,quantity:Math.max(1,a.quantity-1)}:a))}>−</button><b>{x.quantity}</b><button disabled={x.stock!==undefined&&x.quantity>=x.stock} onClick={()=>save(items.map((a,j)=>j===i?{...a,quantity:a.stock===undefined?a.quantity+1:Math.min(a.stock,a.quantity+1)}:a))}>+</button></div><strong className="cart-line-total">₹{x.price*x.quantity}</strong></article>)}</div></section><aside className="cart-summary"><h2>Order Summary</h2><div><span>Subtotal</span><b>₹{subtotal}</b></div><div><span>Shipping</span><b className="cart-free">Free</b></div>{coupon?<div><span>Coupon ({coupon.code})</span><b className="cart-free">−₹{discount}</b></div>:<div><span>Discount</span><b>₹0</b></div>}<div className="coupon-box">{coupon?<><p>{coupon.message}</p><button type="button" onClick={()=>{setCoupon(null);setCouponInput('');setCouponMessage('')}}>Remove coupon</button></>:<><label>Apply Coupon<input value={couponInput} onChange={e=>setCouponInput(e.target.value.toUpperCase())} placeholder="Enter coupon code"/></label><button type="button" onClick={apply} disabled={checking}>{checking?'Checking…':'Apply'}</button>{couponMessage&&<small>{couponMessage}</small>}</>}</div><hr/><div className="cart-total"><span>Total</span><b>₹{total}</b></div><form onSubmit={checkout} className="checkout-form"><h3>Checkout details</h3>{[['name','Name'],['phone','Phone'],['address','Address'],['city','City'],['state','State'],['pin_code','Pincode']].map(([n,l])=><label key={n}>{l}<input required name={n}/></label>)}<button>Proceed to Checkout</button></form><Link className="cart-continue" href="/shop">Continue Shopping</Link></aside></div>{done&&<p className="cart-status">{done}</p>}{recs.length>0&&<section className="cart-recommendations"><div><h2>You May Also Like</h2></div><div className="cart-recommendation-grid">{recs.slice(0,6).map(p=><Link href={`/product/${p.slug}`} key={p.id}><div>{p.images[0]?<img src={p.images[0]} alt={p.name}/>:<span>Punjab Hosiery</span>}</div><h3>{p.name}</h3><b>₹{p.retail_price}</b></Link>)}</div></section>}</main>
}
