-- Run in Supabase SQL Editor. This is additive and contains the stock-safe checkout RPC.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users on delete cascade, role text not null default 'customer' check (role in ('customer','admin')), created_at timestamptz default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, category text, retail_price numeric(12,2) not null check(retail_price>=0), wholesale_price numeric(12,2), stock_quantity integer not null default 0 check(stock_quantity>=0), minimum_wholesale_quantity integer not null default 1 check(minimum_wholesale_quantity>0), sizes text[] not null default '{}', colours text[] not null default '{}', images text[] not null default '{}', is_active boolean not null default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), order_number text unique not null, customer_name text not null, phone text not null, whatsapp text, email text, address text not null, city text not null, state text not null, pin_code text not null, notes text, status text not null default 'pending', subtotal numeric(12,2) not null, delivery_charge numeric(12,2) not null default 0, total numeric(12,2) not null, created_at timestamptz default now());
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders on delete cascade, product_id uuid not null references public.products, product_name text not null, unit_price numeric(12,2) not null, quantity integer not null check(quantity>0));
create table if not exists public.wholesale_inquiries (id uuid primary key default gen_random_uuid(), name text not null, business_name text not null, city text not null, state text not null, whatsapp text not null, products_interested text, quantity text, message text, status text default 'new', created_at timestamptz default now());
alter table public.products enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.wholesale_inquiries enable row level security;
create policy "Public may read active products" on public.products for select using (is_active=true);
create or replace function public.place_order(p_customer jsonb,p_items jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare v_order uuid; v_item jsonb; v_product products; v_total numeric:=0; begin for v_item in select * from jsonb_array_elements(p_items) loop select * into v_product from products where id=(v_item->>'product_id')::uuid and is_active=true for update; if not found or v_product.stock_quantity < (v_item->>'quantity')::int then raise exception 'Item unavailable or insufficient stock'; end if; v_total:=v_total+v_product.retail_price*(v_item->>'quantity')::int; end loop; insert into orders(order_number,customer_name,phone,whatsapp,email,address,city,state,pin_code,notes,subtotal,total) values ('PH-'||to_char(now(),'YYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6)),p_customer->>'name',p_customer->>'phone',p_customer->>'whatsapp',p_customer->>'email',p_customer->>'address',p_customer->>'city',p_customer->>'state',p_customer->>'pin_code',p_customer->>'notes',v_total,v_total) returning id into v_order; for v_item in select * from jsonb_array_elements(p_items) loop select * into v_product from products where id=(v_item->>'product_id')::uuid for update; update products set stock_quantity=stock_quantity-(v_item->>'quantity')::int,updated_at=now() where id=v_product.id; insert into order_items(order_id,product_id,product_name,unit_price,quantity) values(v_order,v_product.id,v_product.name,v_product.retail_price,(v_item->>'quantity')::int); end loop; return v_order; end $$;
-- Add your first admin after creating them in Supabase Authentication: update public.profiles set role='admin' where id='YOUR_AUTH_USER_UUID';
