import {NextResponse} from 'next/server';
import {z} from 'zod';
import {supabaseServer} from '@/lib/supabase/server';

async function admin(request:Request){const token=request.headers.get('authorization')?.replace('Bearer ','');if(!token)return null;const db=supabaseServer();const user=await db.auth.getUser(token);if(!user.data.user)return null;const profile=await db.from('profiles').select('role').eq('id',user.data.user.id).single();return profile.data?.role==='admin'?db:null}
const Category=z.object({id:z.string().uuid().optional(),parent_id:z.string().uuid().nullable(),name:z.string().trim().min(2).max(80),slug:z.string().trim().min(2).max(100).optional(),level:z.number().int().min(1).max(3),sort_order:z.number().int().min(0),is_enabled:z.boolean()});
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
export async function GET(request:Request){const db=await admin(request);if(!db)return NextResponse.json({error:'Unauthorized'},{status:401});const result=await db.from('category_nodes').select('*').order('level').order('sort_order');return NextResponse.json(result.data||[])}
export async function POST(request:Request){const db=await admin(request),data=Category.safeParse(await request.json());if(!db)return NextResponse.json({error:'Unauthorized'},{status:401});if(!data.success)return NextResponse.json({error:'Invalid category'},{status:400});const result=await db.from('category_nodes').insert({...data.data,slug:data.data.slug||slugify(data.data.name)}).select().single();return result.error?NextResponse.json({error:result.error.message},{status:400}):NextResponse.json(result.data)}
export async function PATCH(request:Request){const db=await admin(request),data=Category.safeParse(await request.json());if(!db)return NextResponse.json({error:'Unauthorized'},{status:401});if(!data.success||!data.data.id)return NextResponse.json({error:'Invalid category'},{status:400});const {id,...update}=data.data;const result=await db.from('category_nodes').update({...update,slug:update.slug||slugify(update.name)}).eq('id',id).select().single();return result.error?NextResponse.json({error:result.error.message},{status:400}):NextResponse.json(result.data)}
