'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
export type Locale='en'|'hi';
const messages={en:{nav:{women:'Women',men:'Men',kids:'Kids',bedding:'Bedding',newArrivals:'New Arrivals',sale:'Sale',search:'Search',cart:'Cart',wishlist:'Wishlist',home:'Home',wholesale:'Wholesale',contact:'Contact',delivery:'Delivery',returns:'Returns',shopAll:'Shop all'},product:{addToCart:'Add to Cart',buyWhatsApp:'Buy on WhatsApp',size:'Select size',colour:'Colours',quantity:'Quantity',inStock:'In stock',outStock:'Out of stock',onlyLeft:'Only {count} left in stock',sizeGuide:'Size guide',deliveryCheck:'Check delivery by pincode',check:'Check',addWishlist:'Add to wishlist',savedWishlist:'Saved to wishlist',share:'Share',returns:'Easy 30-day returns'},cart:{title:'Your Cart',checkout:'Checkout',placeOrder:'Place Order',name:'Name',phone:'Phone',address:'Address',city:'City',state:'State',pincode:'Pincode',total:'Total',empty:'Your cart is empty.',orderSuccess:'Order placed successfully. We will contact you shortly.'},shop:{catalogue:'CATALOGUE',allCategories:'All categories',allSizes:'All sizes',anyStock:'Any stock',inStock:'In stock',outStock:'Out of stock',minPrice:'Min price',maxPrice:'Max price',apply:'Apply filters',clear:'Clear',noResults:'No products match these filters.'},footer:{shop:'SHOP',help:'HELP',follow:'FOLLOW',track:'Track order',about:'About',wholesale:'Wholesale'},common:{new:'New',sale:'Sale',back:'Back',orderTracking:'Track your order'}},hi:{nav:{women:'महिलाएं',men:'पुरुष',kids:'बच्चे',bedding:'बेडिंग',newArrivals:'नया कलेक्शन',sale:'सेल',search:'खोजें',cart:'कार्ट',wishlist:'पसंदीदा',home:'होम',wholesale:'थोक',contact:'संपर्क',delivery:'डिलीवरी',returns:'रिटर्न',shopAll:'सभी देखें'},product:{addToCart:'कार्ट में जोड़ें',buyWhatsApp:'व्हाट्सऐप पर खरीदें',size:'साइज़ चुनें',colour:'रंग',quantity:'मात्रा',inStock:'स्टॉक में उपलब्ध',outStock:'स्टॉक में नहीं',onlyLeft:'स्टॉक में केवल {count} बचे हैं',sizeGuide:'साइज़ गाइड',deliveryCheck:'पिनकोड से डिलीवरी देखें',check:'जांचें',addWishlist:'पसंदीदा में जोड़ें',savedWishlist:'पसंदीदा में सहेजा गया',share:'शेयर करें',returns:'30 दिन में आसान रिटर्न'},cart:{title:'आपका कार्ट',checkout:'चेकआउट',placeOrder:'ऑर्डर करें',name:'नाम',phone:'फोन',address:'पता',city:'शहर',state:'राज्य',pincode:'पिनकोड',total:'कुल',empty:'आपका कार्ट खाली है।',orderSuccess:'ऑर्डर सफलतापूर्वक किया गया। हम जल्द संपर्क करेंगे।'},shop:{catalogue:'कैटलॉग',allCategories:'सभी श्रेणियां',allSizes:'सभी साइज़',anyStock:'कोई भी स्टॉक',inStock:'स्टॉक में',outStock:'स्टॉक में नहीं',minPrice:'न्यूनतम कीमत',maxPrice:'अधिकतम कीमत',apply:'फ़िल्टर लगाएं',clear:'साफ़ करें',noResults:'इन फ़िल्टर के लिए कोई उत्पाद नहीं मिला।'},footer:{shop:'खरीदारी',help:'सहायता',follow:'फॉलो करें',track:'ऑर्डर ट्रैक करें',about:'हमारे बारे में',wholesale:'थोक'},common:{new:'नया',sale:'सेल',back:'वापस',orderTracking:'ऑर्डर ट्रैक करें'}}} as const;
type Dictionary=typeof messages.en;const Context=createContext<{locale:Locale;t:(key:string,vars?:Record<string,string|number>)=>string;setLocale:(locale:Locale)=>void}>({locale:'en',t:key=>key,setLocale:()=>{}});
function lookup(dict:any,key:string){return key.split('.').reduce((value,part)=>value?.[part],dict)}
export function LanguageProvider({children}:{children:React.ReactNode}){const router=useRouter();const[locale,setLocaleState]=useState<Locale>('en');useEffect(()=>{const saved=localStorage.getItem('ph-language');if(saved==='hi'||saved==='en')setLocaleState(saved)},[]);const value=useMemo(()=>({locale,t:(key:string,vars:Record<string,string|number>={})=>String(lookup(messages[locale],key)||lookup(messages.en,key)||key).replace(/\{(\w+)\}/g,(_,name)=>String(vars[name]??'')),setLocale:(next:Locale)=>{setLocaleState(next);localStorage.setItem('ph-language',next);document.cookie=`ph-language=${next};path=/;max-age=31536000;samesite=lax`;document.documentElement.lang=next;router.refresh()}}),[locale,router]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useI18n=()=>useContext(Context);
export const categoryHindi:Record<string,string>={Women:'महिलाएं',Men:'पुरुष',Kids:'बच्चे',Bedding:'बेडिंग',Kurtis:'कुर्तियां','Kurta Sets':'कुर्ता सेट','Embroidered Kurtis':'कढ़ाई वाली कुर्तियां','Printed Kurtis':'प्रिंटेड कुर्तियां','Daily Wear Kurtis':'रोज़ाना पहनने की कुर्तियां',Shirts:'शर्ट्स','T-Shirts':'टी-शर्ट्स',Jeans:'जींस',Bedsheets:'बेडशीट',Blankets:'कंबल',Comforters:'कंफर्टर'};
