import Link from 'next/link';
import {supabaseServer} from '@/lib/supabase/server';
import type {Product} from '@/lib/types';
import {getProductImage} from '@/lib/product-variants';
import FeaturedCarousel from './featured-carousel';

const categories=[['Women','/shop?category=Women','one'],['Men','/shop?category=Men','three'],['Kids','/shop?category=Kids','four'],['New Arrivals','/shop?new=true','two'],['Bedding','/shop?category=Bedding','five'],['Sale','/shop?sale=true','six']];
const rupees=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
function ProductGrid({title,kicker,products,href}:{title:string;kicker:string;products:Product[];href:string}){return <section className="home-products" data-reveal><div className="home-section-heading"><div><p>{kicker}</p><h2>{title}</h2></div><Link href={href}>View all →</Link></div>{products.length?<div className="home-product-grid">{products.slice(0,5).map(p=>{const image=getProductImage(p);return <Link href={`/product/${p.slug}`} className="product-card" key={p.id}>{image?<img src={image} alt={p.name}/>:<div className="product-image-empty">Punjab Hosiery</div>}<div className="product-copy"><p>{p.category||'Punjab Hosiery'}</p><h3>{p.name}</h3><b>{rupees(p.retail_price)}</b></div></Link>})}</div>:<div className="empty-products">New products are coming soon. Add products from Admin and they will appear here.</div>}</section>}
export default async function Home(){let products:Product[]=[];try{let r=await supabaseServer().from('products').select('*').eq('is_active',true).order('created_at',{ascending:false}).limit(20);products=r.data||[]}catch{}let newItems=products.filter(p=>p.is_new_arrival);let saleItems=products.filter(p=>p.is_on_sale);let featured=products.slice(0,8).map(p=>({id:p.id,name:p.name,slug:p.slug,category:p.category,retail_price:p.retail_price,image:getProductImage(p)}));return <main><section className="compact-hero"><img src="/hero-family.png" alt="Indian family wearing Punjab Hosiery clothing"/><div className="hero-shade"/><div className="compact-hero-content"><p>STYLE FOR EVERYDAY INDIA</p><h1>Fashion &amp; comfort for the <i>whole family.</i></h1><h2>Clothing for women, men and kids, plus bedding and home essentials — retail and wholesale across India.</h2><div className="hero-ctas"><Link href="/shop">Shop Now <b>→</b></Link><a href="https://wa.me/919219879392?text=Hello%20Punjab%20Hosiery%2C%20I%20want%20to%20make%20a%20wholesale%20inquiry." target="_blank" rel="noreferrer">Wholesale Inquiry</a></div></div></section><section className="compact-trust"><span>Pan-India Delivery</span><span>Easy 30-Day Returns</span><span>Retail + Wholesale</span></section><div className="compact-location">Himalaya Farm, Rampur Road, Haldwani — Near Medical College.</div><section className="compact-categories" data-reveal><div className="home-section-heading"><div><p>SHOP THE STORE</p><h2>Shop by Category</h2></div><Link href="/shop">View all products →</Link></div><div className="compact-category-grid">{categories.map(([name,href,position])=><Link href={href} className={`category-card card-${position}`} key={name}><span>{name}</span><b>Shop now <i>↗</i></b></Link>)}</div></section><ProductGrid title="New Arrivals" kicker="JUST IN" products={newItems.length?newItems:products} href="/shop?new=true"/><section className="campaign-banner campaign-winter" data-reveal><div><p>SEASONAL EDIT</p><h2>Winter essentials for every day.</h2><Link href="/shop">Shop collection →</Link></div></section><section className="featured-products" data-reveal><div className="home-section-heading"><div><p>MOST LOVED</p><h2>Trending Now</h2></div><Link href="/shop">View all →</Link></div><FeaturedCarousel products={featured}/></section><section className="campaign-banner campaign-wholesale" data-reveal><div><p>FOR SHOPKEEPERS</p><h2>Wholesale deals, made simple.</h2><a href="https://wa.me/919219879392?text=Hello%20Punjab%20Hosiery%2C%20I%20want%20to%20make%20a%20wholesale%20inquiry.">Chat on WhatsApp →</a></div></section>{saleItems.length>0&&<ProductGrid title="Sale" kicker="SPECIAL PRICES" products={saleItems} href="/shop?sale=true"/>}</main>}
