import {notFound} from 'next/navigation';

type Section={heading:string;body:string[]};
type Page={title:string;intro:string;sections:Section[]};
const business={name:'Punjab Hosiery',address:'Himalaya Farm, Rampur Road, Haldwani, near Medical College, Uttarakhand, India',phone:'+91 9219879392'};
const shippingSections:Section[]=[
  {heading:'Order processing',body:['Orders are checked for product availability, address details and confirmation before dispatch. We may contact you if any detail needs clarification. Processing normally begins after confirmation; the exact dispatch date is shared when the order is confirmed.']},
  {heading:'Estimated delivery',body:['Estimated delivery timing depends on the delivery pincode, courier service, weather and product availability. The pincode checker provides a general estimate of 3–7 business days; it is an estimate, not a guaranteed delivery date.']},
  {heading:'Dispatch and tracking',body:['When tracking is available, courier and tracking details are added to your order status. Delivery availability, charges and expected delivery information can vary by location, order size and product availability.']},
  {heading:'Receiving your order',body:['Please check the package and items after delivery. If you need help with an order, contact us with your order ID and registered phone number.']}
];
const pages:Record<string,Page>={
  about:{title:'About Punjab Hosiery',intro:'Punjab Hosiery is a local, family-run store in Haldwani, Uttarakhand, serving households, customers and shopkeepers with everyday clothing, hosiery and home essentials.',sections:[
    {heading:'A store you can reach',body:[`You can visit or contact ${business.name} at ${business.address}. Our physical-store presence means you can speak with a real team for help with products, sizing, orders and wholesale requirements.`]},
    {heading:'For everyday needs',body:['We offer retail and wholesale clothing, hosiery, blankets, bedsheets and related everyday products. We aim to make choosing practical, comfortable products straightforward for the whole family.']},
    {heading:'Retail and wholesale support',body:['Whether you are buying for your home or sourcing for a shop, we are happy to guide you on available products and bulk enquiries. Pan-India delivery is available, subject to order confirmation and serviceability.']}
  ]},
  contact:{title:'Contact Us',intro:'We are happy to help with product questions, orders, wholesale enquiries, delivery support and returns.',sections:[{heading:'Punjab Hosiery',body:[business.address,`Call or WhatsApp: ${business.phone}`]},{heading:'How to reach us',body:['Please keep your order ID ready when contacting us about an existing order. For wholesale enquiries, share the product or category, approximate quantity and your city so we can assist you efficiently.']}]},
  shipping:{title:'Shipping & Delivery Policy',intro:'Punjab Hosiery provides Pan-India delivery for confirmed retail and wholesale orders.',sections:shippingSections},
  delivery:{title:'Shipping & Delivery Policy',intro:'Punjab Hosiery provides Pan-India delivery for confirmed retail and wholesale orders.',sections:shippingSections},
  returns:{title:'Return, Exchange & Refund Policy',intro:'Punjab Hosiery offers a 7-day return window from the date of delivery for eligible items.',sections:[
    {heading:'7-day eligibility',body:['To request a return or exchange, contact us within 7 days of delivery with your order ID, registered phone number and a clear description of the reason. Returned items must be unused, unwashed, undamaged and returned with original tags, packaging and any included accessories.']},
    {heading:'Items that cannot be returned',body:['For hygiene and safety, innerwear, socks and other personal-use items are not eligible once opened or used. Customized, altered, clearance/final-sale items and products damaged after delivery may also be excluded. If an item arrives damaged, incorrect or defective, please contact us promptly with clear photos so we can review it.']},
    {heading:'Return shipping and exchange',body:['Return shipping responsibility is confirmed after we review the request. Where the item was sent incorrectly, defective or damaged in transit, Punjab Hosiery will guide you on the return process. For preference-based returns or exchanges, return shipping may be the customer’s responsibility. Exchanges are subject to availability.']},
    {heading:'Refund timing',body:['After a returned item reaches us and passes inspection, any approved refund is initiated to the original payment method or another mutually confirmed method. Bank, card, UPI and payment-provider processing times can vary; we will share confirmation once the refund is initiated.']},
    {heading:'How to request help',body:[`Contact ${business.name} at ${business.phone} with your order ID, registered phone number and photographs where relevant. Please keep the product and packaging safely until we confirm the next steps.`]}
  ]},
  cancellation:{title:'Cancellation Policy',intro:'If you need to cancel an order, please contact Punjab Hosiery as soon as possible.',sections:[{heading:'Cancellation requests',body:['Share your order ID and registered phone number when requesting cancellation. A cancellation request can be accommodated only when the order has not progressed beyond the stage where cancellation is possible.']},{heading:'Confirmation',body:['We will confirm whether your cancellation request can be accepted after checking the order status. If you have received the item already, please contact us for guidance under the Return, Exchange & Refund Policy.']}]},
  privacy:{title:'Privacy Policy',intro:'Punjab Hosiery respects your privacy and uses customer information only for serving you and completing your request.',sections:[{heading:'Information we use',body:['We may use the name, phone number, delivery address, order details and enquiry details you provide to process orders, respond to enquiries, provide support and manage delivery.']},{heading:'How information is shared',body:['We share only the information needed with service providers involved in fulfilling an order, such as delivery partners. We do not sell your personal information.']},{heading:'Your choices',body:[`For questions about your information or to request support, contact ${business.name} at ${business.phone}.`]}]},
  terms:{title:'Terms & Conditions',intro:'These terms apply when you browse, enquire about or place an order with Punjab Hosiery.',sections:[{heading:'Products and prices',body:['Product images and descriptions are provided to help you choose. Product availability, prices and other details may change before an order is confirmed.']},{heading:'Orders',body:['An order or enquiry is subject to confirmation by Punjab Hosiery. Please provide correct contact and delivery information so we can process your request.']},{heading:'Use of this website',body:['Please use this website only for lawful shopping, enquiries and communication. Do not misuse the website, interfere with its operation or provide false order information.']},{heading:'Support',body:[`For help with any order, product or policy, contact ${business.name} at ${business.phone}.`]}]}
};
export default async function Info({params}:{params:Promise<{info:string}>}){const page=pages[(await params).info];if(!page)notFound();return <main className="mx-auto max-w-4xl px-[5%] py-16"><p className="text-xs font-bold tracking-widest text-[#ae7636]">PUNJAB HOSIERY</p><h1 className="mt-2 text-5xl">{page.title}</h1><section className="form mt-8 leading-7 text-slate-700"><p className="text-lg leading-8">{page.intro}</p>{page.sections.map(section=><div className="mt-8" key={section.heading}><h2 className="text-2xl font-bold text-[#17271e]">{section.heading}</h2>{section.body.map(paragraph=><p className="mt-3" key={paragraph}>{paragraph}</p>)}</div>)}</section></main>}
