import {notFound} from 'next/navigation';
type Section={heading:string;body:string[]};type Page={title:string;intro:string;sections:Section[]};
const business={name:'Punjab Hosiery',address:'Himalaya Farm, Rampur Road, Haldwani, near Medical College, Uttarakhand, India',phone:'+91 9219879392'};
const pages:Record<string,Page>={
about:{title:'About Punjab Hosiery',intro:'Punjab Hosiery offers retail and wholesale clothing, hosiery, blankets, bedsheets and related everyday products, with Pan-India delivery.',sections:[{heading:'Our store',body:[`Visit or contact ${business.name} at ${business.address}. We are here to help customers and shopkeepers find suitable products for their needs.`]}]},
contact:{title:'Contact Us',intro:'We are happy to help with product questions, orders, wholesale enquiries, delivery support and returns.',sections:[{heading:'Punjab Hosiery',body:[business.address,`Call or WhatsApp: ${business.phone}`]},{heading:'How to reach us',body:['Please keep your order ID ready when contacting us about an existing order. For wholesale enquiries, share the product or category, approximate quantity and your city so we can assist you efficiently.']}]},
shipping:{title:'Shipping & Delivery Policy',intro:'Punjab Hosiery provides Pan-India delivery for retail and wholesale orders.',sections:[{heading:'Order confirmation',body:['Orders are subject to product availability and confirmation. We may contact you if any order detail, address or product availability needs clarification before dispatch.']},{heading:'Delivery details',body:['Delivery availability, charges and expected delivery information are shown or confirmed during the order process. These details can vary by delivery location, order size and product availability.']},{heading:'Receiving your order',body:['Please check the package and items after delivery. If you need help with an order, contact us with your order ID and registered phone number.']}]},
delivery:{title:'Shipping & Delivery Policy',intro:'Punjab Hosiery provides Pan-India delivery for retail and wholesale orders.',sections:[{heading:'Order confirmation',body:['Orders are subject to product availability and confirmation. We may contact you if any order detail, address or product availability needs clarification before dispatch.']},{heading:'Delivery details',body:['Delivery availability, charges and expected delivery information are shown or confirmed during the order process. These details can vary by delivery location, order size and product availability.']},{heading:'Receiving your order',body:['Please check the package and items after delivery. If you need help with an order, contact us with your order ID and registered phone number.']}]},
returns:{title:'Return, Exchange & Refund Policy',intro:'We want you to feel confident when shopping with Punjab Hosiery.',sections:[{heading:'Requesting help',body:['If you need to request a return, exchange or refund, please contact us with your order ID, registered phone number and a clear description of the issue.']},{heading:'Review of requests',body:['Return, exchange and refund requests are reviewed based on the item, its condition and the order details. We will share the available next steps after reviewing your request.']},{heading:'Product condition',body:['Please keep the product, packaging and any included items safely until we confirm the next steps. This helps us review the request properly.']}]},
cancellation:{title:'Cancellation Policy',intro:'If you need to cancel an order, please contact Punjab Hosiery as soon as possible.',sections:[{heading:'Cancellation requests',body:['Share your order ID and registered phone number when requesting cancellation. A cancellation request can be accommodated only when the order has not progressed beyond the stage where cancellation is possible.']},{heading:'Confirmation',body:['We will confirm whether your cancellation request can be accepted after checking the order status. If you have received the item already, please contact us for guidance under the Return, Exchange & Refund Policy.']}]},
privacy:{title:'Privacy Policy',intro:'Punjab Hosiery respects your privacy and uses customer information only for serving you and completing your request.',sections:[{heading:'Information we use',body:['We may use the name, phone number, delivery address, order details and enquiry details you provide to process orders, respond to enquiries, provide support and manage delivery.']},{heading:'How information is shared',body:['We share only the information needed with service providers involved in fulfilling an order, such as delivery partners. We do not sell your personal information.']},{heading:'Your choices',body:[`For questions about your information or to request support, contact ${business.name} at ${business.phone}.`]}]},
terms:{title:'Terms & Conditions',intro:'These terms apply when you browse, enquire about or place an order with Punjab Hosiery.',sections:[{heading:'Products and prices',body:['Product images and descriptions are provided to help you choose. Product availability, prices and other details may change before an order is confirmed.']},{heading:'Orders',body:['An order or enquiry is subject to confirmation by Punjab Hosiery. Please provide correct contact and delivery information so we can process your request.']},{heading:'Use of this website',body:['Please use this website only for lawful shopping, enquiries and communication. Do not misuse the website, interfere with its operation or provide false order information.']},{heading:'Support',body:[`For help with any order, product or policy, contact ${business.name} at ${business.phone}.`]}]},
};
export default async function Info({params}:{params:Promise<{info:string}>}){const page=pages[(await params).info];if(!page)notFound();return <main className="mx-auto max-w-4xl px-[5%] py-16"><p className="text-xs font-bold tracking-widest text-[#ae7636]">PUNJAB HOSIERY</p><h1 className="mt-2 text-5xl">{page.title}</h1><section className="form mt-8 leading-7 text-slate-700"><p className="text-lg leading-8">{page.intro}</p>{page.sections.map(section=><div className="mt-8" key={section.heading}><h2 className="text-2xl font-bold text-[#17271e]">{section.heading}</h2>{section.body.map(paragraph=><p className="mt-3" key={paragraph}>{paragraph}</p>)}</div>)}</section></main>}
