import type {Product,ProductVariant} from './types';
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const rawVariants=(value:unknown):any[]=>{if(Array.isArray(value))return value;if(typeof value==='string'){try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed:[]}catch{return[]}}return[]};
export const getVariants=(product:Product):ProductVariant[]=>rawVariants(product.variants).map(variant=>({id:variant.id||`${product.id}-${slugify(variant.color||'variant')}${variant.size?`-${slugify(variant.size)}`:''}`,color:variant.color||variant.colour||'Colour',colorHex:variant.colorHex||variant.hex||variant.color_hex||'#777777',size:variant.size||undefined,image:variant.image||variant.image_url||variant.url||'',sku:variant.sku||`${slugify(product.slug).toUpperCase()}-${slugify(variant.color||variant.colour||'variant').toUpperCase()}`,stock:Number(variant.stock??variant.stock_quantity??(variant.in_stock===false?0:product.stock_quantity))})).filter(variant=>Boolean(variant.image));
export const getAvailableVariants=(product:Product)=>getVariants(product).filter(variant=>variant.stock>0);
export const getDefaultVariant=(product:Product)=>getAvailableVariants(product)[0]||getVariants(product)[0];
export const getVariantById=(product:Product,variantId:string|null|undefined)=>getVariants(product).find(variant=>variant.id===variantId);
export const getVariantImage=(product:Product,variantId?:string|null)=>getVariantById(product,variantId)?.image||getDefaultVariant(product)?.image||product.images[0]||'';
export const getProductImage=(product:Product)=>getDefaultVariant(product)?.image||product.images[0]||'';
export function validateProductVariants(product:Pick<Product,'name'|'variants'>){const seen=new Set<string>();for(const variant of product.variants||[]){if(!variant.id)throw new Error('Variant missing id');if(!variant.color)throw new Error('Variant missing color');if(!variant.image)throw new Error('Variant missing image');if(!variant.sku)throw new Error('Variant missing SKU');if(!Number.isInteger(variant.stock)||variant.stock<0)throw new Error('Variant has invalid stock');const key=`${variant.color.toLowerCase()}|${(variant.size||'').toLowerCase()}`;if(seen.has(key))throw new Error('Duplicate colour and size variant');seen.add(key)}}
